# Generated by Django 5.1.6 on 2025-02-13 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snp', '0003_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.CharField(max_length=256),
        ),
    ]
