# Generated by Django 5.1.4 on 2025-02-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snp', '0004_alter_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
